### ISSUE TITLE
複数の円が検出できない問題について

### ISSUE THREAD

**Issue by Shuma-s58** [open-rdc/2024_Intelligent_Robot-Team_Rock#2]
ある場面において、hough変換によって複数の円が検出できないといった問題が起きたのでissueを立てます。

# 開発環境
* ubuntu 20.04.6 LTS
* python 3.8.10
* opencv-python  4.10.0.82
* numpy 1.17.4

使用したコードは最後に示します。

## 複数の円が検出できなかった画像(opencvにより作成)
* hough変換前:
![test2-same_duplication_30-105](https://github.com/open-rdc/2024_Intelligent_Robot-Team_Rock/assets/115678656/ed85b4ee-8a27-4eb9-961a-db131f5aaee0)
* hough変換後:
![cir_test](https://github.com/open-rdc/2024_Intelligent_Robot-Team_Rock/assets/115678656/3df129f1-1ad0-4c2e-a81d-f848393909b0)

## 複数の円が検出された画像(LibreOffice Drawにより作成)
* hough変換前:
![17-37-04-2](https://github.com/open-rdc/2024_Intelligent_Robot-Team_Rock/assets/115678656/f8db09d9-4127-4bff-bd17-80649753f094)

* hough変換後:
![cir_17-37](https://github.com/open-rdc/2024_Intelligent_Robot-Team_Rock/assets/115678656/fc4f3d19-ca4d-4f4f-9935-47850c56e66c)

## hough変換のコード:

```
import cv2
import numpy as np

# 画像の読み込み
image = cv2.imread('/home/shumas_sub/ball_detection/same_duplication/same_duplication_30-105.jpg')

gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

circles = cv2.HoughCircles(gray_image, 
                           cv2.HOUGH_GRADIENT,
                           dp=1,
                           minDist=120, 
                           param1=50,
                           param2=30,
                           minRadius=0,
                           maxRadius=1000)
if circles is not None:
    # circles変数をfloatからintに変換
    circles = np.uint16(np.around(circles))

    for circle in circles[0, :]:
        # 円周を描画する
        cv2.circle(image, (circle[0], circle[1]), circle[2], (0, 165, 255), 5)
        # 中心点を描画する
        cv2.circle(image, (circle[0], circle[1]), 2, (0, 0, 255), 3)
else:
    print("No Circles")

# show_radius
print(circles)

cv2.imwrite('/home/shumas_sub/ball_detection/same_duplication/cir_same_duplication_30-105.jpg', image)

```
## 画像作成のコード:
```
import cv2
import numpy as np

print(cv2.__version__)
# 3.3.0

img = np.full((210, 210, 3), 255, dtype=np.uint8)

cv2.circle(img, (135, 105), 30, (0, 0, 0), thickness=-1, lineType=cv2.LINE_AA)

cv2.circle(img, (60, 135), 30, (0, 0, 0), thickness=-1, lineType=cv2.LINE_AA)

cv2.imwrite('/home/shumas_sub/ball_detection/same_duplication/test2-same_duplication_30-105.jpg', img)

```

**Comment by yasuohayashibara** [comment]
@Shuma-s58 
判明しました．
`minDist`の値が大きすぎます．
以下の値にすると2つ検出します．

minDist=10

**Comment by Shuma-s58** [comment]
自分の環境でも２つ検出できることが確認できました。
ありがとうございます。

問題が解決したので、このissueに関してはここで閉じます。
